name: Build and Deploy

on:
  push:
    branches:
      - "dev"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
   
      - name: Push updated src folder to dev-build branch
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
        run: |
      
           git fetch origin dev-build:dev-build || true # Ignore error if it doesn't exist
           
           if git branch --list | grep -q "dev-build"; then
               git checkout dev-build
           else
               git checkout -b dev-build
           fi

           git config user.name "Prathm0025"
           git config user.email "prathamesh@underpinservices.com"
           
           # Remove the existing src folder if it exists and copy the new one
           rm -rf src
           git checkout dev -- src

           # Stage only the src folder
           git add src
           git commit -m "update src folder" || echo "No changes to commit"
           git push --force origin dev-build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ./src/**/*.js
